# fly.toml app configuration file generated for asssuretrac-resume-eval on 2025-08-14T06:03:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'asssuretrac-resume-eval'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
